version: '3.8'
services:
    pyspark:
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        env_file:
            - .env
        volumes:
            - ./:/var/project
        command: ./runtests.sh
