site_name: Delta Utils
theme:
    name: readthedocs
repo_url: https://github.com/bulv1ne/delta_utils
docs_dir: docs
nav:
    - Home: 'README.md'
    - 'installation.md'
    - 'User Guide':
      - 'usage.md'
      - 'core.md'
    - 'About':
          - Issue Tracker: 'https://github.com/bulv1ne/delta_utils/issues'
          - 'CHANGELOG.md'
          - License: 'LICENSE.md'
plugins:
    - search
    - RootFiles:
          files:
              - 'README.md'
              - 'CHANGELOG.md'
              - 'LICENSE.md'
