site_name: Delta Utils
theme:
    name: readthedocs
repo_url: https://github.com/bulv1ne/delta_utils
nav:
    - Home: 'README.md'
    - 'About':
          - Issue Tracker: 'https://github.com/bulv1ne/delta_utils/issues'
          - 'CHANGELOG.md'
          - License: 'LICENSE.md'
plugins:
    - RootFiles:
          files:
              - 'README.md'
              - 'CHANGELOG.md'
              - 'LICENSE.md'
