[tool.poetry]
name = "delta_utils"
version = "0.1.0"
description = ""
authors = ["Niels Lemmens <1936122+bulv1ne@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/bulv1ne/delta_utils"
documentation = "https://delta-utils.readthedocs.io/en/latest/"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "*"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
flake8 = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
databricks-connect = "9.1.*"
mkdocs = "*"
moto = {extras = ["s3"], version = "*"}
boto3-stubs = {extras = ["s3"], version = "*"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."mkdocs.plugins"]
RootFiles = "mkdocs_plugins.files:RootFiles"
