# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  artifact:
    name: Create artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry pipx
    - name: poetry build
      run: |
        poetry build
    - name: Upload file to s3 bucket
      run: |
        pipx run --spec awscli aws s3 cp --recursive --acl=public-read ./dist/ s3://${{ secrets.S3_BUCKET }}/deltatableextra/
      env:
       AWS_REGION: 'eu-west-1'
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
