# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  artifact:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry pipx
    - name: poetry build
      run: |
        poetry build
    - name: Docker build test image
      env:
        DATABRICKS_CONNECT: ${{ secrets.DATABRICKS_CONNECT }}
      run: |
        echo "$DATABRICKS_CONNECT" > .databricks-connect
        docker-compose build pyspark
    - name: Databricks connect test
      env:
        TEST_DIR: ${{ secrets.TEST_DIR }}
      run: |
        echo "TEST_DIR=$TEST_DIR" > .env
        docker-compose run pyspark databricks-connect
    - name: Test
      run: |
        docker-compose run pyspark
