# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Git tag version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Tag version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Is last commit bump version
      id: version_number
      continue-on-error: true
      run: |
        # Check if the commit message has "Bump version from" in it
        git show HEAD -q | tail -n 1 | grep -q "Bump version from"
        OUTPUT=$(git show HEAD -q | tail -n 1 | awk 'NF>1{print $NF}') &&
        echo "::set-output name=OUTPUT::$OUTPUT"
    - name: Git tag & push
      if: steps.version_number.outputs.OUTPUT != ''
      run: |
        git tag ${{ steps.version_number.outputs.OUTPUT }}
        git push --tags
